#!/usr/bin/env node
// Regenerate src/forge/catalog.ts from Forge's OpenAPI spec:
//   curl -o /tmp/forge-openapi.json https://forge.laravel.com/api/docs.openapi
//   node scripts/build-catalog.mjs /tmp/forge-openapi.json
import { readFileSync, writeFileSync } from 'fs'

const spec = JSON.parse(readFileSync(process.argv[2], 'utf8'))
const schemas = spec.components?.schemas ?? {}
const ORG = '/orgs/{organization}'
// Org administration is out of scope for this server.
const EXCLUDED_TAGS = new Set(['Roles', 'Teams', 'Server Credentials'])
const EXCLUDED_PATHS = [/^\/teams/, /^\/roles/, /^\/permissions/, /^\/predefined-roles/]

function deref(s) {
  return s?.$ref ? schemas[s.$ref.split('/').pop()] ?? {} : s ?? {}
}

function bodyFields(op) {
  const content = op.requestBody?.content ?? {}
  const schema = deref(Object.values(content)[0]?.schema)
  const required = new Set(schema.required ?? [])
  return Object.keys(schema.properties ?? {}).map(k => (required.has(k) ? `${k}*` : k))
}

const rows = []
for (const [rawPath, ops] of Object.entries(spec.paths)) {
  const path = rawPath.startsWith(ORG) ? rawPath.slice(ORG.length) || '/' : rawPath
  if (EXCLUDED_PATHS.some(r => r.test(path))) continue
  for (const [method, op] of Object.entries(ops)) {
    if (!['get', 'post', 'put', 'patch', 'delete'].includes(method)) continue
    if ((op.tags ?? []).some(t => EXCLUDED_TAGS.has(t))) continue
    rows.push([method.toUpperCase(), path, op.summary ?? '', bodyFields(op).join(',')])
  }
}

const out = `// Generated by scripts/build-catalog.mjs from Forge's OpenAPI spec. Do not edit.
// [method, path (relative to /orgs/{organization}), summary, body fields (* = required)]
export const CATALOG: [string, string, string, string][] = ${JSON.stringify(rows)}
`
writeFileSync(new URL('../src/forge/catalog.ts', import.meta.url), out)
console.log(`catalog: ${rows.length} endpoints`)
